### ISSUE TITLE
Bug: GitHub Sync with Dev Spaces

### ISSUE THREAD

**Issue by kyetter** [kyetter/ansible-devspace-demo#6]
## Description
In the devspace, git requires configuration of username and email for each new devspace and a personal access token is required every time you want to interact with git (commit, push, etc.)

## Documentation
I've tried following these steps to resolve the issue without success: https://www.eclipse.org/che/docs/stable/administration-guide/configuring-oauth-2-for-github/

**Comment by jeffcpullen** [comment]
https://github.com/redhat-developer/devspaces-demo << relevant?
