### ISSUE TITLE
Bug: oc should be included

### ISSUE THREAD

**Issue by kyetter** [kyetter/ansible-devspace-demo#8]
## Description
For the oc_connection molecule demo, once molecule prepare is run, the user needs to run "source ~/.bashrc" to have oc recognized on the path. Jeff proposed 3 options for getting rid of this: 
-  include oc in the container image
- include oc in the dev file so that its downloaded and stored somewhere already in the path
-  put together some shell script in the image that is executed (hopefully automatically on launch)

**Comment by jeffcpullen** [comment]
This was completed with previous merge
